language: node_js

node_js:
  - 16

services:
  - mongodb
  - redis-server

install: 
  - npm ci

before_script:
  - sleep 15 # MongoDB may not immediately accept connections
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script: 
  - npm test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-southeast-1"
  app: "moody-quotes"
  env: "Moodyquotes-env"
  bucket_name: "moody-quotes-bucket"
  on:
    branch: main
