language: node_js
node_js:
  - 16
script:
  - npm ci
  - npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "ap-southeast-1"
  app: "my-quotes"
  env: "Myquotes-env-1"
  bucket_name: "bucket-my-quotes"
  on:
    branch: main
